trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Publish nightly packages
  branches:
    include:
    - main
  always: false

variables:
- template: templates/vars.yaml

extends:
  ${{ if eq(variables['System.TeamProject'], 'GitHub - PR Builds') }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  ${{ else }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool: 
      name: $(pool_name)
      image: orleans-build-image
      os: windows
    stages:
    - stage: build_test
      displayName: Build and Tests
      jobs:
      - template: templates/build.yaml
        parameters:
          build_configuration: Release
          version_prefix: '8.1.0'
          include_suffix: true
          version_suffix: nightly.$(Build.BuildNumber)
          codesign: true
          publish_nightly: true
          skip_test: true
