pool: 'orleans-pr-hosted-pool'

trigger: none

parameters:
  - name: test_frameworks
    displayName: Test Frameworks
    type: object
    default:
    - 6.0.x
    - 5.0.x
    - 3.1.x

variables:
  BuildConfiguration: Release

jobs:
- job: Build
  displayName: Build and create NuGet packages
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: './Build.ps1'
- job: BVT
  displayName: Test BVT
  dependsOn: Build
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: './Build.ps1'
  - ${{ each framework in parameters.test_frameworks }}:
    - task: UseDotNet@2
      displayName: Install ${{framework}}
      inputs:
        version: ${{framework}}
  - task: BatchScript@1
    displayName: Test
    inputs:
      filename: 'Test.cmd'
- job: Functional
  displayName: Test Functional
  dependsOn: Build
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: './Build.ps1'
  - ${{ each framework in parameters.test_frameworks }}:
    - task: UseDotNet@2
      displayName: Install ${{framework}}
      inputs:
        version: ${{framework}}
  - task: BatchScript@1
    displayName: Test
    inputs:
      filename: 'TestAll.cmd'