pool: 'orleans-pr-hosted-pool'

trigger: none

variables:
  BuildConfiguration: Release

jobs:
- job: Build
  displayName: Build and create NuGet packages
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: './Build.ps1'
- job: Test BVT
  displayName: Test BVT
  dependsOn: Build
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: './Build.ps1'
  - task: BatchScript@1
    inputs:
      filename: 'Test.cmd'
- job: Test Functional
  displayName: Test Functional
  dependsOn: Build
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: './Build.ps1'
  - task: BatchScript@1
    inputs:
      filename: 'TestAll.cmd'